---
title: 'Gypsy: profile-based gypsum application recommendation'
# author: "Chloe Lai"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## `r input$fieldName`

### `r paste0('Crop: ', input$cropType)`

`r paste0('Total gypsum required to reach non-limiting ESP (t/ha):', round(out_list()$gTotal, digits = 2))`



```{r table, echo=FALSE}
df <- out_list()$df
df[,1] <- c('Gypsum application rates (t/ha)', 'Final ESP (0-20 cm)', 'Final ESP (20-50 cm)','Surplus Gypsum (t/ha)',
             'Gypsum cost, spread (\\$/ha)', 'Additional yield p.a. (t/ha)', 'Additional income p.a. (\\$/ha)',
             'Net benefit over time period (\\$/ha)')

kable(df, escape = T, format = 'html')%>%
  column_spec(1, bold = T) %>%
  kable_styling(
    font_size = 15,
    bootstrap_options = c("striped", "hover", "condensed","responsive")
  )

    
```



```{r plot, echo=FALSE}
plot(out_list()$gypRate, out_list()$ben.net, type = 'l',
     xlab = 'Gypsum rate (t/ha)', ylab = 'Estimated net benefit over time period ($/ha)')
abline(v = 10, col = 'red')
abline(h = 0, col = 'navy')
```


